import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */

  // tutorialSidebar: [
  //   'intro',
  //   {
  //     type: 'category',
  //     label: 'introduction',
  //     collapsible: true, //可折疊
  //     collapsed: true,
  //     link: {
  //       type: 'generated-index',
  //       title: 'Introduction',
  //       description:
  //         '中文測試 The following tutorials cover the basic and most important features and APIs of PcapPlusPlus and should give a good understanding of how to work with the library',
  //       slug: 'introduction',
  //     },
  //     items: [
  //       'introduction/gipsense-api-user-manual',
  //       'introduction/gipsense-map-api-user-manual',
  //       'introduction/gipsens-events-notification',
  //     ],
  //   },
  // ],
};

export default sidebars;
